### ISSUE TITLE
Are you not supporting sdk versions bellow 21?

### ISSUE THREAD

**Issue by tnaffh** [cesarferreira/MaterialComponent.Banner#1]
`Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [com.github.cesarferreira:MaterialComponent.Banner:0.10.0] ~/.gradle/caches/transforms-1/files-1.1/MaterialComponent.Banner-0.10.0.aar/52a922d193d70143bd826d69d0b25e96/AndroidManifest.xml as the library might be using APIs not available in 16
	Suggestion: use a compatible library with a minSdk of at most 16,
		or increase this project's minSdk version to at least 21,
		or use tools:overrideLibrary="com.cesar.materialcomponents" to force usage (may lead to runtime failures)`

**Comment by cesarferreira** [comment]
Just made a new release, check `0.11.0`
