### ISSUE TITLE
Compatibility for lower APIs

### ISSUE THREAD

**Issue by WebTiger89** [cesarferreira/MaterialComponent.Banner#5]
Thanks for your investigation. Can you maybe add compatibility for lower APIs like 21 because the action methods expect a functional reference (for non-kotlin users) which  requires API 24.

Thanks in advance

EDIT: I guess I'm just doing something wrong. Can you give an example on how to implement the action method without kotlin?

**Comment by cesarferreira** [comment]
minSDK is `16` https://github.com/cesarferreira/MaterialComponent.Banner/blob/master/banner/build.gradle


I haven't done java in almost a year but if I remember correctly they're just anonymous classes with syntactic sugar
